/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ProxyDiamond, ProxyDiamondInterface } from "../ProxyDiamond";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
    _diamondFacet: "ERC20ProxyFacet",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
    _diamondFacet: "ERC20ProxyFacet",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_initializationContractAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_calldata",
        type: "bytes",
      },
    ],
    name: "InitializationFunctionReverted",
    type: "error",
    _diamondFacet: "ProxyDiamond",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
    ],
    name: "allowance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ERC20ProxyFacet",
    _diamondSelector: "0xdd62ed3e",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "approve",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "ERC20ProxyFacet",
    _diamondSelector: "0x095ea7b3",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ERC20ProxyFacet",
    _diamondSelector: "0x70a08231",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "pure",
    type: "function",
    _diamondFacet: "ERC20ProxyFacet",
    _diamondSelector: "0x313ce567",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_erc1155Address",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_childTokenId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "string",
        name: "_symbol",
        type: "string",
      },
    ],
    name: "initializeERC20Proxy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "ERC20ProxyFacet",
    _diamondSelector: "0x4887f13f",
  },
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ERC20ProxyFacet",
    _diamondSelector: "0x06fdde03",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ProxyDiamond",
    _diamondSelector: "0x01ffc9a7",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ERC20ProxyFacet",
    _diamondSelector: "0x95d89b41",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ERC20ProxyFacet",
    _diamondSelector: "0x18160ddd",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "ERC20ProxyFacet",
    _diamondSelector: "0xa9059cbb",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "ERC20ProxyFacet",
    _diamondSelector: "0x23b872dd",
  },
] as const;

export class ProxyDiamond__factory {
  static readonly abi = _abi;
  static createInterface(): ProxyDiamondInterface {
    return new Interface(_abi) as ProxyDiamondInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ProxyDiamond {
    return new Contract(address, _abi, runner) as unknown as ProxyDiamond;
  }
}
