/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProxyDiamond } from "./ProxyDiamond";
export * as factories from "./factories";
export { ProxyDiamond__factory } from "./factories/ProxyDiamond__factory";
